name: Docker Build & Run Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t test-image .

    - name: Run container and verify it starts
      run: |
        docker run -d --name test-container test-image
        sleep 5
        docker ps -a
        docker logs test-container

    - name: Cleanup
      if: always()
      run: |
        docker stop test-container || true
        docker rm test-container || true
